### ISSUE TITLE
Mobile Friendly Optimisation

### ISSUE THREAD

**Issue by ShubhamPalriwala** [feyre-2001/CollegePredictor#2]

**Comment by ShubhamPalriwala** [comment]
Added in Todo

**Comment by DanCanetti** [comment]
What sort of optimisation are you looking for on this?

**Comment by ShubhamPalriwala** [comment]
Hey @DanCanetti , 
So right now if you look at our webpage: collegepredictor.ml
It doesn't fit well when it comes to smaller screen devices.
We're looking for anything that makes our tool more accessible for the students !

**Comment by DanCanetti** [comment]
I'd be happy to pick this up for you as part of hacktoberfest? I'll probably just just some flex box to stack it on mobile so you're not losing that text anymore that's on the left on desktop?

**Comment by ShubhamPalriwala** [comment]
Sounds Good !
Try to get that text on the bottom or on top because having it along with the Form might just fill up the page.

**Comment by DanCanetti** [comment]
If the form is the key part (which it clearly is) I can stack it with the text beneath 😄

**Comment by ShubhamPalriwala** [comment]
Cool !

**Comment by AmitKarnam** [comment]
Hey @ShubhamPalriwala Can I try working on improving the UI/UX of the website?

**Comment by DanCanetti** [comment]
@ShubhamPalriwala I'm trying push up a new branch with the first part of the responsive work and I'm getting a permissions error `Permission to feyre-2001/CollegePredictor.git denied to DanCanetti`. Any thoughts?

**Comment by ShubhamPalriwala** [comment]
> Hey @ShubhamPalriwala Can I try working on improving the UI/UX of the website?
> 
> 
> 
> 

Hey @AmitKarnam , @DanCanetti is already working on making a better front end for us !

If you still wanna contribute to us then please open another issue and we will be glad to have you in our team !

**Comment by ShubhamPalriwala** [comment]
@DanCanetti , I think you need to make a PR first before pushing it to our branch !
Make sure you create yourname-branch and while making a PR !

**Comment by DanCanetti** [comment]
> @DanCanetti , I think you need to make a PR first before pushing it to our branch !
> Make sure you create yourname-branch and while making a PR !

My bad! I hadn't forked the repo I'd cloned it to local! I have the responsive work complete for page one and will have page two done in the next couple of days. If @AmitKarnam would like to pick it up from there that's okay with me? The more the merrier right!

**Comment by AmitKarnam** [comment]
That would be great @DanCanetti , Would like to hear your plans abt UI changes, that would help me come up with new ides!

**Comment by ShubhamPalriwala** [comment]
Glad to see both of you helping us together ! 
@DanCanetti  @AmitKarnam GG guys !

**Comment by AmitKarnam** [comment]
@ShubhamPalriwala I think the responsive fix of @DanCanetti has not been merged. It would be easy for me to add UI changes after the responsive code has been merged. In the mean time I'll try a few changes and put it up here for further discussion.

**Comment by ShubhamPalriwala** [comment]
@DanCanetti  do you want me to accept your PR on 1st of October under the Hacktoberfest or shall I do it now?
Anything works for me :)

**Comment by DanCanetti** [comment]
The 1st would be appreciated! ☺️ as long as that's okay with everyone else!

**Comment by ShubhamPalriwala** [comment]
Yeah its totally okay with us ! You deserve it ! Hope @AmitKarnam youre okay with this too !

**Comment by AmitKarnam** [comment]
Anything is fine for me! Thanks @DanCanetti  for letting me work on this.

**Comment by AmitKarnam** [comment]
Hey @ShubhamPalriwala ,Wat is the command to setup a local server?
 I have forked and cloned the repo and have been working on it in my desktop. I wanted to run a local server just to go through the changes I have made.

**Comment by LaxmanJonchhen12** [comment]
Can I work on responsiveness of site?

**Comment by ShubhamPalriwala** [comment]
@AmitKarnam , @DanCanetti has done incredible work and his changes have been pushed #18 to our master branch !
You can take over now !

**Comment by DanCanetti** [comment]
> @AmitKarnam , @DanCanetti has done incredible work and his changes have been pushed #18 to our master branch !
> You can take over now !

Thank you so much and happy to help! Good luck with the project!

**Comment by AmitKarnam** [comment]
@ShubhamPalriwala do you have any particular UI changes in mind? or can I go ahead with my plan and then you can review it.

**Comment by ShubhamPalriwala** [comment]
@AmitKarnam right now we dont have anything so we'll be glad to see what you're up to !

**Comment by AmitKarnam** [comment]
@ShubhamPalriwala  Really Sorry for the late response.
 I have made small improvements to the UI, will continue to add changes if and required as I progress on my learning.

**Comment by ShubhamPalriwala** [comment]
No Issues @AmitKarnam !
The changes look good !
Thanks for contributing !

**Comment by AmitKarnam** [comment]
@ShubhamPalriwala I was going through the changes I made to your website and observed that the next button on the landing page seems to be pretty small by mobile standards. 

It looks like this
![1](https://user-images.githubusercontent.com/56480746/97338814-d067ca00-18a7-11eb-93a9-3b1a6571a1eb.jpg)

In style css I made the following changes and it works!
@media (max-width: 400px)
.right-container footer #next {
    /* width: 100%; */
    border-radius: 0;
}

After the changes 
![2](https://user-images.githubusercontent.com/56480746/97338943-fab98780-18a7-11eb-90a9-08bc75fe17f4.jpg)

But I'm not sure about how this works, so thought to share this before i can raise a PR.

**Comment by ShubhamPalriwala** [comment]
@AmitKarnam yeah I saw this too!
We're pleased that you have fixed this !
Please make a PR!

**Comment by AmitKarnam** [comment]
@ShubhamPalriwala I have raised a PR for this.
I am not sure how this fix works, I discovered it through trail and error. I thoroughly checked it and found no harm for the page contents. If any is found later please revert back this commit. In the mean time ill go through and find how exactly this fix works!
Thanks.

**Comment by ShubhamPalriwala** [comment]
Sounds cool!
