### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by VishwaduttMS** [feyre-2001/CollegePredictor#43]
This website is not working since the recent commit. Please look into this

**Comment by ShubhamPalriwala** [comment]
Hey @VishwaduttMS, the website is down since our domain has expired! Thanks for letting us know.

**Comment by VishwaduttMS** [comment]
Thanks for the reply! Can you please let me know when the website will be back again and running...

**Comment by ShubhamPalriwala** [comment]
Hey @VishwaduttMS! We do not plan to host it currently. However, you can run the website locally yourself. Steps to do so are provided in the README

**Comment by VishwaduttMS** [comment]
Yeah! I tried to run the website locally. But I'm getting the following error. It would be great if you can help me on this please
<img width="680" alt="error" src="https://user-images.githubusercontent.com/61235944/124065781-0e2f7a80-da55-11eb-9253-f264a041edd9.PNG">

**Comment by vishalbhatd123456** [comment]
Hi @ShubhamPalriwala  can you please guide over the virtual environment setup and the docker run? I too am facing similar issue that @VishwaduttMS  is currently facing. Would be really thankful if you can provide more details for the installation of setting virtual env and running on docker, as this is quite new and need this quite urgently! Thanks in advance

**Comment by VishwaduttMS** [comment]
Thank you!
